spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: flixmovie
    password: flixmovie0908
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movieflix:
  security:
    secret: dd0f0f79aefb4c129f13c2c40fa56fd232c73d9d6f5bbda3cc64a9607df6cbe4

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html